### ISSUE TITLE
should AUC fail if vectors have mismatched length?

### ISSUE THREAD

**Issue by pavopax** [mfrasco/Metrics#13]
I think it should?

```r
> ## pred is longer than true
> pred <- c(rep(0, 1), rep(1, 100))
> true <- c(rep(0, 50), rep(1, 50))
> Metrics::auc(true, pred)
[1] 0.52
```

R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

**Comment by mfrasco** [comment]
Thanks for opening an issue around this topic. I appreciate the interest in the package.

Since all of the other functions in the package except for `auc` throw a warning when the length of the longer vector is not a multiple of the length of the shorter vector. I agree that `auc` should also throw a warning to the user in these cases. If you want to open a PR that adds the warning message, that would be great.

However, I am hesitant to throw a fatal error for two reasons.
1. R rarely, if ever, throws an error on functions that when vectors of different lengths are passed as arguments. For better or worse, the idea of recycling is at the core of R. Since most users of R expect this behavior from R, I wouldn't want this package to deviate.
2. Backwards compatibility. I don't want to break existing code that was relying on this behavior, even if this behavior doesn't make sense.

Does that make sense? What do you think?

**Comment by pavopax** [comment]
thanks! my reply:

I didn't check everything in this package, but if you say that most other functions throw errors when there is length mismatch, then so should `auc`. perhaps instead of an error, we can make it a notification that still returns a value?

**Comment by mfrasco** [comment]
I'm a bit confused by your comment. I said that the other functions throw warnings, not errors. To stay consistent with the other functions, I think that `auc` should also throw a warning.

**Comment by pavopax** [comment]
Yea sounds good, sorry for misreading! Agree with your last assessment.

(sent from a mobile device)

**Comment by mfrasco** [comment]
I am closing out this issue. `auc` will now throw a warning on vectors of different lengths.
